"""
Blog models for Nash-Security License Store.
Posts are auto-generated by AI Agent or manually by admin.
"""
from django.db import models
from django.utils.text import slugify
from django.utils import timezone


class Category(models.Model):
    """Blog post category."""
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True, max_length=100)
    description = models.TextField(blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ['name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Tag(models.Model):
    """Blog post tag."""
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(unique=True, max_length=50)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Post(models.Model):
    """Blog post — can be AI-generated or manually written."""

    class Status(models.TextChoices):
        DRAFT = 'draft', 'Draft'
        PUBLISHED = 'published', 'Published'
        SCHEDULED = 'scheduled', 'Scheduled'

    class Source(models.TextChoices):
        AI_AGENT = 'ai_agent', 'AI Agent'
        ADMIN = 'admin', 'Admin Manual'

    title = models.CharField(max_length=300)
    slug = models.SlugField(unique=True, max_length=300)
    excerpt = models.TextField(
        max_length=500, blank=True, default='',
        help_text='Short summary for preview cards'
    )
    content = models.TextField(help_text='Full article content (Markdown supported)')
    featured_image = models.URLField(
        blank=True, default='',
        help_text='URL of the featured image'
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='posts'
    )
    tags = models.ManyToManyField(Tag, blank=True, related_name='posts')

    # SEO
    meta_title = models.CharField(max_length=200, blank=True, default='')
    meta_description = models.CharField(max_length=300, blank=True, default='')

    # Status & scheduling
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.DRAFT)
    source = models.CharField(max_length=20, choices=Source.choices, default=Source.ADMIN)
    published_at = models.DateTimeField(null=True, blank=True)

    # AI Agent metadata
    ai_topic = models.CharField(max_length=200, blank=True, default='')
    ai_keywords = models.JSONField(default=list, blank=True)
    ai_read_time = models.PositiveIntegerField(
        default=5, help_text='Estimated reading time in minutes'
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-published_at', '-created_at']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)[:300]
        if self.status == self.Status.PUBLISHED and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    @property
    def is_published(self):
        return self.status == self.Status.PUBLISHED

    @property
    def word_count(self):
        return len(self.content.split())

    @property
    def read_time(self):
        words = self.word_count
        return max(1, words // 200)


class Comment(models.Model):
    """Blog post comment."""
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author_name = models.CharField(max_length=100)
    author_email = models.EmailField()
    content = models.TextField(max_length=2000)
    is_approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.author_name} on {self.post.title}'
