# Generated by Django 5.0.14 on 2026-07-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price_toman', models.PositiveIntegerField(help_text='Price in Iranian Toman')),
                ('duration_days', models.PositiveIntegerField(help_text='License duration in days')),
                ('max_cameras', models.PositiveIntegerField(default=1, help_text='Maximum number of cameras')),
                ('features', models.JSONField(blank=True, default=dict, help_text='JSON object of product features')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['price_toman'],
            },
        ),
    ]
