# Generated by Django 5.0.14 on 2026-07-27 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('order_id', models.CharField(blank=True, default='', max_length=100)),
                ('license_key', models.CharField(blank=True, default='', max_length=64)),
                ('hardware_fingerprint', models.CharField(blank=True, default='', max_length=256)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'License Log',
                'verbose_name_plural': 'License Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_key', models.CharField(db_index=True, help_text='Unique generated license key', max_length=64, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('hardware_fingerprint', models.CharField(blank=True, default='', help_text='Hardware fingerprint bound to this license', max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='orders.order')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
